apiVersion: v1
kind: Service
metadata:
  name: nidhi-service
spec:
  selector:
    app: nidhi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use ClusterIP if not exposing externally
